/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package base;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import operation.TovarOperationImpl;
//import types.Buketi;
//import operation.BuketiOperationImpl;
import types.Tovar;
/**
 *
 * @author Karina
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    TovarOperationImpl tovarOperation = new TovarOperationImpl();
    //BuketiOperationImpl buketiOperation = new BuketiOperationImpl();
       static DefaultTableModel model = new DefaultTableModel();
       
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgTabl = new javax.swing.JDialog();
        tlBar = new javax.swing.JToolBar();
        btnAdd = new javax.swing.JButton();
        Jspersad = new javax.swing.JToolBar.Separator();
        btnDecide = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnRemove = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txt = new javax.swing.JTextField();
        dlgCat = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        btnFlover = new javax.swing.JButton();
        btnBuketi = new javax.swing.JButton();
        btnPostav = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        dlgAddFlover = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        scrPriceF = new javax.swing.JScrollBar();
        lblPriceInfoF = new javax.swing.JLabel();
        spnKolF = new javax.swing.JSpinner();
        cmbNameF = new javax.swing.JComboBox();
        btnAddF = new javax.swing.JButton();
        btnCancelF = new javax.swing.JButton();
        dlgAddBuketi = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        scrPriceB = new javax.swing.JScrollBar();
        lblPriceInfoB = new javax.swing.JLabel();
        spnKolB = new javax.swing.JSpinner();
        cmbNameB = new javax.swing.JComboBox();
        btnAddB = new javax.swing.JButton();
        btnCancelB = new javax.swing.JButton();
        dlgPost = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        btnRM = new javax.swing.JButton();
        btnSJ = new javax.swing.JButton();
        btnKM = new javax.swing.JButton();
        dlgRM = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        scrPriceRM = new javax.swing.JScrollBar();
        lblPriceInfoRM = new javax.swing.JLabel();
        spnKolRM = new javax.swing.JSpinner();
        cmbNameRM = new javax.swing.JComboBox();
        btnAddRM = new javax.swing.JButton();
        btnCancelRM = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        dlgSJ = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        scrPriceSJ = new javax.swing.JScrollBar();
        lblPriceInfoSJ = new javax.swing.JLabel();
        spnKolSJ = new javax.swing.JSpinner();
        cmbNameSJ = new javax.swing.JComboBox();
        btnAddSJ = new javax.swing.JButton();
        btnCancelSJ = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        dlgKM = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        scrPriceKM = new javax.swing.JScrollBar();
        lblPriceInfoKM = new javax.swing.JLabel();
        spnKolKM = new javax.swing.JSpinner();
        cmbNameKM = new javax.swing.JComboBox();
        btnAddKM = new javax.swing.JButton();
        btnCancelKM = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        dlgContacts = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Buy = new javax.swing.JButton();
        Contacts = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        dlgTabl.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                dlgTablWindowOpened(evt);
            }
        });

        tlBar.setRollover(true);

        btnAdd.setText("Добавить");
        btnAdd.setFocusable(false);
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        tlBar.add(btnAdd);
        tlBar.add(Jspersad);

        btnDecide.setText("Вычислить");
        btnDecide.setFocusable(false);
        btnDecide.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDecide.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDecide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecideActionPerformed(evt);
            }
        });
        tlBar.add(btnDecide);
        tlBar.add(jSeparator2);

        btnRemove.setText("Удалить");
        btnRemove.setFocusable(false);
        btnRemove.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRemove.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        tlBar.add(btnRemove);
        tlBar.add(jSeparator3);

        btnExit.setText("Выход");
        btnExit.setFocusable(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        tlBar.add(btnExit);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "п/п", "Название", "Цена", "Количсетво", "Сумма"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl);

        jLabel2.setText("Сумма товаров");

        javax.swing.GroupLayout dlgTablLayout = new javax.swing.GroupLayout(dlgTabl.getContentPane());
        dlgTabl.getContentPane().setLayout(dlgTablLayout);
        dlgTablLayout.setHorizontalGroup(
            dlgTablLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tlBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(dlgTablLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel2)
                .addGap(102, 102, 102)
                .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgTablLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );
        dlgTablLayout.setVerticalGroup(
            dlgTablLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgTablLayout.createSequentialGroup()
                .addComponent(tlBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(dlgTablLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Категории");

        btnFlover.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnFlover.setText("Цветы");
        btnFlover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFloverActionPerformed(evt);
            }
        });

        btnBuketi.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnBuketi.setText("Букеты");
        btnBuketi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuketiActionPerformed(evt);
            }
        });

        btnPostav.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnPostav.setText("Поставшики");
        btnPostav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostavActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnCancel.setText("Отмена");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgCatLayout = new javax.swing.GroupLayout(dlgCat.getContentPane());
        dlgCat.getContentPane().setLayout(dlgCatLayout);
        dlgCatLayout.setHorizontalGroup(
            dlgCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgCatLayout.createSequentialGroup()
                .addGroup(dlgCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgCatLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(dlgCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuketi, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(btnFlover, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(dlgCatLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(btnPostav))
                    .addGroup(dlgCatLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        dlgCatLayout.setVerticalGroup(
            dlgCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgCatLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addComponent(btnFlover)
                .addGap(18, 18, 18)
                .addComponent(btnBuketi)
                .addGap(18, 18, 18)
                .addComponent(btnPostav)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addGap(26, 26, 26))
        );

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Название");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Количество");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Цена");

        scrPriceF.setMaximum(500);
        scrPriceF.setMinimum(15);
        scrPriceF.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        scrPriceF.setToolTipText("");
        scrPriceF.setValue(50);
        scrPriceF.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                scrPriceFAdjustmentValueChanged(evt);
            }
        });

        lblPriceInfoF.setText("50");

        spnKolF.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        cmbNameF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Роза", "Тюльпан", "Орхидея", "Хризонтема", "Ромашка", "Голандская роза" }));
        cmbNameF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNameFActionPerformed(evt);
            }
        });

        btnAddF.setText("Добавить");
        btnAddF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFActionPerformed(evt);
            }
        });

        btnCancelF.setText("Отмена");
        btnCancelF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgAddFloverLayout = new javax.swing.GroupLayout(dlgAddFlover.getContentPane());
        dlgAddFlover.getContentPane().setLayout(dlgAddFloverLayout);
        dlgAddFloverLayout.setHorizontalGroup(
            dlgAddFloverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgAddFloverLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(dlgAddFloverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgAddFloverLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(60, 60, 60)
                        .addComponent(scrPriceF, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dlgAddFloverLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(49, 49, 49)
                        .addComponent(cmbNameF, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dlgAddFloverLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(50, 50, 50)
                        .addComponent(spnKolF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgAddFloverLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPriceInfoF)
                .addGap(141, 141, 141))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgAddFloverLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnAddF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelF, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        dlgAddFloverLayout.setVerticalGroup(
            dlgAddFloverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgAddFloverLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgAddFloverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(dlgAddFloverLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cmbNameF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(dlgAddFloverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgAddFloverLayout.createSequentialGroup()
                        .addGroup(dlgAddFloverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(spnKolF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgAddFloverLayout.createSequentialGroup()
                        .addComponent(lblPriceInfoF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrPriceF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(dlgAddFloverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddF)
                    .addComponent(btnCancelF))
                .addGap(34, 34, 34))
        );

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Название");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Количество");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Цена");

        scrPriceB.setMaximum(5000);
        scrPriceB.setMinimum(800);
        scrPriceB.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        scrPriceB.setToolTipText("");
        scrPriceB.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                scrPriceBAdjustmentValueChanged(evt);
            }
        });

        lblPriceInfoB.setText("800");

        spnKolB.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        cmbNameB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Романтика", "Весна", "Для тебя", "Чудеса", "Студент", "Мажорский" }));

        btnAddB.setText("Добавить");
        btnAddB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBActionPerformed(evt);
            }
        });

        btnCancelB.setText("Отмена");
        btnCancelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgAddBuketiLayout = new javax.swing.GroupLayout(dlgAddBuketi.getContentPane());
        dlgAddBuketi.getContentPane().setLayout(dlgAddBuketiLayout);
        dlgAddBuketiLayout.setHorizontalGroup(
            dlgAddBuketiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgAddBuketiLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(dlgAddBuketiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgAddBuketiLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(60, 60, 60)
                        .addComponent(scrPriceB, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dlgAddBuketiLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(49, 49, 49)
                        .addComponent(cmbNameB, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dlgAddBuketiLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(50, 50, 50)
                        .addComponent(spnKolB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgAddBuketiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPriceInfoB)
                .addGap(141, 141, 141))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgAddBuketiLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btnAddB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelB, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        dlgAddBuketiLayout.setVerticalGroup(
            dlgAddBuketiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgAddBuketiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgAddBuketiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(dlgAddBuketiLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cmbNameB, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(dlgAddBuketiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgAddBuketiLayout.createSequentialGroup()
                        .addGroup(dlgAddBuketiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(spnKolB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgAddBuketiLayout.createSequentialGroup()
                        .addComponent(lblPriceInfoB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrPriceB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(dlgAddBuketiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelB)
                    .addComponent(btnAddB))
                .addGap(34, 34, 34))
        );

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setText("Поставшики");

        btnRM.setText("РозаМимоза");
        btnRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRMActionPerformed(evt);
            }
        });

        btnSJ.setText("Цветы жизни");
        btnSJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSJActionPerformed(evt);
            }
        });

        btnKM.setText("Кировский мясокомбинат)))");
        btnKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgPostLayout = new javax.swing.GroupLayout(dlgPost.getContentPane());
        dlgPost.getContentPane().setLayout(dlgPostLayout);
        dlgPostLayout.setHorizontalGroup(
            dlgPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgPostLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(dlgPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSJ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgPostLayout.createSequentialGroup()
                .addGap(0, 106, Short.MAX_VALUE)
                .addComponent(btnKM)
                .addGap(99, 99, 99))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgPostLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(123, 123, 123))
        );
        dlgPostLayout.setVerticalGroup(
            dlgPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgPostLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel10)
                .addGap(30, 30, 30)
                .addComponent(btnRM)
                .addGap(18, 18, 18)
                .addComponent(btnSJ)
                .addGap(18, 18, 18)
                .addComponent(btnKM)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Название");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("Количество");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("Цена");

        scrPriceRM.setMaximum(6000);
        scrPriceRM.setMinimum(15);
        scrPriceRM.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        scrPriceRM.setToolTipText("");
        scrPriceRM.setValue(50);
        scrPriceRM.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                scrPriceRMAdjustmentValueChanged(evt);
            }
        });

        lblPriceInfoRM.setText("50");

        spnKolRM.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        cmbNameRM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Роза", "Голандская роза", "Романтика" }));
        cmbNameRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNameRMActionPerformed(evt);
            }
        });

        btnAddRM.setText("Добавить");
        btnAddRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRMActionPerformed(evt);
            }
        });

        btnCancelRM.setText("Отмена");
        btnCancelRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelRMActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel20.setText("РозаМимоза");

        javax.swing.GroupLayout dlgRMLayout = new javax.swing.GroupLayout(dlgRM.getContentPane());
        dlgRM.getContentPane().setLayout(dlgRMLayout);
        dlgRMLayout.setHorizontalGroup(
            dlgRMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgRMLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnAddRM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(btnCancelRM, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgRMLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dlgRMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgRMLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(60, 60, 60)
                        .addComponent(scrPriceRM, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dlgRMLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(49, 49, 49)
                        .addComponent(cmbNameRM, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dlgRMLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(50, 50, 50)
                        .addComponent(spnKolRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgRMLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPriceInfoRM)
                        .addGap(111, 111, 111)))
                .addGap(29, 29, 29))
            .addGroup(dlgRMLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dlgRMLayout.setVerticalGroup(
            dlgRMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgRMLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(dlgRMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(dlgRMLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cmbNameRM, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(dlgRMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgRMLayout.createSequentialGroup()
                        .addGroup(dlgRMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(spnKolRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgRMLayout.createSequentialGroup()
                        .addComponent(lblPriceInfoRM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrPriceRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(dlgRMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddRM)
                    .addComponent(btnCancelRM))
                .addGap(34, 34, 34))
        );

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("Название");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("Количество");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("Цена");

        scrPriceSJ.setMaximum(6000);
        scrPriceSJ.setMinimum(15);
        scrPriceSJ.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        scrPriceSJ.setToolTipText("");
        scrPriceSJ.setValue(50);
        scrPriceSJ.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                scrPriceSJAdjustmentValueChanged(evt);
            }
        });

        lblPriceInfoSJ.setText("50");

        spnKolSJ.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        cmbNameSJ.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Орхидея", "Хризонтема", "Мажорский", "Для тебя" }));
        cmbNameSJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNameSJActionPerformed(evt);
            }
        });

        btnAddSJ.setText("Добавить");
        btnAddSJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSJActionPerformed(evt);
            }
        });

        btnCancelSJ.setText("Отмена");
        btnCancelSJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelSJActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel21.setText("Цветы жизни");

        javax.swing.GroupLayout dlgSJLayout = new javax.swing.GroupLayout(dlgSJ.getContentPane());
        dlgSJ.getContentPane().setLayout(dlgSJLayout);
        dlgSJLayout.setHorizontalGroup(
            dlgSJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgSJLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnAddSJ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(btnCancelSJ, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgSJLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dlgSJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgSJLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(60, 60, 60)
                        .addComponent(scrPriceSJ, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dlgSJLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(49, 49, 49)
                        .addComponent(cmbNameSJ, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dlgSJLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(50, 50, 50)
                        .addComponent(spnKolSJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgSJLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPriceInfoSJ)
                        .addGap(111, 111, 111)))
                .addGap(25, 25, 25))
            .addGroup(dlgSJLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dlgSJLayout.setVerticalGroup(
            dlgSJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgSJLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(dlgSJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(dlgSJLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cmbNameSJ, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(dlgSJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgSJLayout.createSequentialGroup()
                        .addGroup(dlgSJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(spnKolSJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgSJLayout.createSequentialGroup()
                        .addComponent(lblPriceInfoSJ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrPriceSJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(dlgSJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddSJ)
                    .addComponent(btnCancelSJ))
                .addGap(34, 34, 34))
        );

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setText("Название");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel18.setText("Количество");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel19.setText("Цена");

        scrPriceKM.setMaximum(500);
        scrPriceKM.setMinimum(15);
        scrPriceKM.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        scrPriceKM.setToolTipText("");
        scrPriceKM.setValue(50);
        scrPriceKM.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                scrPriceKMAdjustmentValueChanged(evt);
            }
        });

        lblPriceInfoKM.setText("50");

        spnKolKM.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        cmbNameKM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Тюльпан", "Ромашка", "Весна", "Чудеса", "Студент" }));
        cmbNameKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNameKMActionPerformed(evt);
            }
        });

        btnAddKM.setText("Добавить");
        btnAddKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddKMActionPerformed(evt);
            }
        });

        btnCancelKM.setText("Отмена");
        btnCancelKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelKMActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel22.setText("Кировский мясокомбинат");

        javax.swing.GroupLayout dlgKMLayout = new javax.swing.GroupLayout(dlgKM.getContentPane());
        dlgKM.getContentPane().setLayout(dlgKMLayout);
        dlgKMLayout.setHorizontalGroup(
            dlgKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgKMLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnAddKM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelKM, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgKMLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(dlgKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgKMLayout.createSequentialGroup()
                        .addGroup(dlgKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dlgKMLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(60, 60, 60)
                                .addComponent(scrPriceKM, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dlgKMLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(49, 49, 49)
                                .addComponent(cmbNameKM, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dlgKMLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(50, 50, 50)
                                .addComponent(spnKolKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgKMLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPriceInfoKM)
                                .addGap(111, 111, 111)))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgKMLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(61, 61, 61))))
        );
        dlgKMLayout.setVerticalGroup(
            dlgKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgKMLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(dlgKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(dlgKMLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cmbNameKM, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(dlgKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgKMLayout.createSequentialGroup()
                        .addGroup(dlgKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(spnKolKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgKMLayout.createSequentialGroup()
                        .addComponent(lblPriceInfoKM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrPriceKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(dlgKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddKM)
                    .addComponent(btnCancelKM))
                .addGap(34, 34, 34))
        );

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextArea1.setRows(4);
        jTextArea1.setText("Горячая линия: +7 (909) 777 77 77\nWhatsapp: \t   +7 (909) 777 77 77\nViber:\t   +7 (909) 777 77 77\nE-mail:\t   FloverShop@shop.com");
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout dlgContactsLayout = new javax.swing.GroupLayout(dlgContacts.getContentPane());
        dlgContacts.getContentPane().setLayout(dlgContactsLayout);
        dlgContactsLayout.setHorizontalGroup(
            dlgContactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        dlgContactsLayout.setVerticalGroup(
            dlgContactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Главное меню");

        Buy.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Buy.setText("КУПИТЬ");
        Buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyActionPerformed(evt);
            }
        });

        Contacts.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Contacts.setText("КОНТАКТЫ");
        Contacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactsActionPerformed(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        Exit.setText("Выход");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setText("SHOP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Buy, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(Contacts, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Contacts, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buy, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(Exit)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ContactsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactsActionPerformed
    dlgContacts.setSize(300, 320);
    dlgContacts.setLocationRelativeTo(null);
    dlgContacts.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_ContactsActionPerformed

    private void BuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyActionPerformed
    dlgTabl.setSize(300, 320);
    dlgTabl.setLocationRelativeTo(null);
    dlgTabl.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_BuyActionPerformed

    private void cmbNameFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNameFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNameFActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    dlgCat.setSize(300, 320);
    dlgCat.setLocationRelativeTo(null);
    dlgCat.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDecideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecideActionPerformed
    txt.setText(Integer.toString(tovarOperation.getSumOfTovar()));        // TODO add your handling code here:
    }//GEN-LAST:event_btnDecideActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
    dlgTabl.setVisible(false);       // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
    setDefaultCloseOperation(this.EXIT_ON_CLOSE);
    System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed

    private void dlgTablWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dlgTablWindowOpened
        model = (DefaultTableModel)tbl.getModel();
        /*doVivod(tovarOperation.getListOfTovar());
        doVivodB(buketiOperation.getListOfBuketi());*/

        // TODO add your handling code here:
    }//GEN-LAST:event_dlgTablWindowOpened

    private void scrPriceFAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_scrPriceFAdjustmentValueChanged
            lblPriceInfoF.setText(Integer.toString((int) scrPriceF.getValue()));        // TODO add your handling code here:
    }//GEN-LAST:event_scrPriceFAdjustmentValueChanged

    private void scrPriceBAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_scrPriceBAdjustmentValueChanged
        lblPriceInfoB.setText(Integer.toString((int) scrPriceB.getValue()));        // TODO add your handling code here:
    }//GEN-LAST:event_scrPriceBAdjustmentValueChanged

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
    dlgCat.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCancelFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelFActionPerformed
    dlgAddFlover.setVisible(false);           // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelFActionPerformed

    private void btnCancelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelBActionPerformed
    dlgAddBuketi.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelBActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
    DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        try
        {
             int SelectRowIndex =tbl.getSelectedRow();
            model.removeRow(SelectRowIndex);
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnAddFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFActionPerformed
    dlgAddFlover.setVisible(false);
        // д.б. код для проверки полей на правильность ввода
        Tovar el;
            el = new Tovar(cmbNameF.getSelectedItem().toString(), (int) spnKolF.getValue(), scrPriceF.getValue());
        doVivod(tovarOperation.addNewTovar(el));
    }                                           

    private void doVivod(List<Tovar> lstTovar){
        doClearTable();
        int i = 1;
        for(Tovar tovar: lstTovar){
            Object[] rowData = new Object[5];
            rowData[0] = i++;
            rowData[1] = tovar.getName();
            rowData[2] = tovar.getPrice();
            rowData[3] = tovar.getKol();
            rowData[4] = tovar.getPrice() * tovar.getKol();
            model.addRow(rowData);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddFActionPerformed

    private void btnAddBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBActionPerformed
    dlgAddBuketi.setVisible(false);
        // д.б. код для проверки полей на правильность ввода
        Tovar el;
        
            el = new Tovar(cmbNameB.getSelectedItem().toString(), (int) spnKolB.getValue(), scrPriceB.getValue());
        
            
      
        doVivod(tovarOperation.addNewTovar(el));        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddBActionPerformed

    private void btnFloverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFloverActionPerformed
    dlgAddFlover.setSize(300, 320);
    dlgAddFlover.setLocationRelativeTo(null);
    dlgAddFlover.setVisible(true); 
    dlgCat.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btnFloverActionPerformed

    private void btnBuketiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuketiActionPerformed
    dlgAddBuketi.setSize(300, 320);
    dlgAddBuketi.setLocationRelativeTo(null);
    dlgAddBuketi.setVisible(true); 
    dlgCat.setVisible(false);     // TODO add your handling code here:
    }//GEN-LAST:event_btnBuketiActionPerformed

    private void scrPriceRMAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_scrPriceRMAdjustmentValueChanged
       lblPriceInfoRM.setText(Integer.toString((int) scrPriceRM.getValue())); // TODO add your handling code here:
    }//GEN-LAST:event_scrPriceRMAdjustmentValueChanged

    private void cmbNameRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNameRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNameRMActionPerformed

    private void btnAddRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRMActionPerformed
      dlgRM.setVisible(false);
        // д.б. код для проверки полей на правильность ввода
        Tovar el;
            el = new Tovar(cmbNameRM.getSelectedItem().toString(), (int) spnKolRM.getValue(), scrPriceRM.getValue());
        doVivod(tovarOperation.addNewTovar(el));
    }//GEN-LAST:event_btnAddRMActionPerformed

    private void btnCancelRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelRMActionPerformed
       dlgRM.setVisible(false);   // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelRMActionPerformed

    private void scrPriceSJAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_scrPriceSJAdjustmentValueChanged
      lblPriceInfoSJ.setText(Integer.toString((int) scrPriceSJ.getValue()));  // TODO add your handling code here:
    }//GEN-LAST:event_scrPriceSJAdjustmentValueChanged

    private void cmbNameSJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNameSJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNameSJActionPerformed

    private void btnAddSJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSJActionPerformed
         dlgSJ.setVisible(false);
        // д.б. код для проверки полей на правильность ввода
        Tovar el;
            el = new Tovar(cmbNameSJ.getSelectedItem().toString(), (int) spnKolSJ.getValue(), scrPriceSJ.getValue());
        doVivod(tovarOperation.addNewTovar(el));// TODO add your handling code here:
    }//GEN-LAST:event_btnAddSJActionPerformed

    private void btnCancelSJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelSJActionPerformed
       dlgSJ.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelSJActionPerformed

    private void scrPriceKMAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_scrPriceKMAdjustmentValueChanged
       lblPriceInfoKM.setText(Integer.toString((int) scrPriceKM.getValue())); // TODO add your handling code here:
    }//GEN-LAST:event_scrPriceKMAdjustmentValueChanged

    private void cmbNameKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNameKMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNameKMActionPerformed

    private void btnAddKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddKMActionPerformed
       dlgKM.setVisible(false);
        // д.б. код для проверки полей на правильность ввода
        Tovar el;
            el = new Tovar(cmbNameKM.getSelectedItem().toString(), (int) spnKolKM.getValue(), scrPriceKM.getValue());
        doVivod(tovarOperation.addNewTovar(el));  // TODO add your handling code here:
    }//GEN-LAST:event_btnAddKMActionPerformed

    private void btnCancelKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelKMActionPerformed
       dlgKM.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelKMActionPerformed

    private void btnRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRMActionPerformed
    dlgRM.setSize(300, 320);
    dlgRM.setLocationRelativeTo(null);
    dlgRM.setVisible(true); 
    dlgPost.setVisible(false);//  // TODO add your handling code here:
    }//GEN-LAST:event_btnRMActionPerformed

    private void btnSJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSJActionPerformed
    dlgSJ.setSize(300, 320);
    dlgSJ.setLocationRelativeTo(null);
    dlgSJ.setVisible(true); 
    dlgPost.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSJActionPerformed

    private void btnKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKMActionPerformed
    dlgKM.setSize(300, 320);
    dlgKM.setLocationRelativeTo(null);
    dlgKM.setVisible(true); 
    dlgPost.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnKMActionPerformed

    private void btnPostavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostavActionPerformed
    dlgPost.setSize(300, 320);
    dlgPost.setLocationRelativeTo(null);
    dlgPost.setVisible(true); 
    dlgCat.setVisible(false);     // TODO add your handling code here:
    }//GEN-LAST:event_btnPostavActionPerformed
       /* private void doVivodB(List<Buketi> lstBuketi){
        doClearTable();
        int i = 1;
        for(Buketi buketi: lstBuketi){
            Object[] rowData = new Object[5];
            rowData[0] = i++;
            rowData[1] = buketi.getNameB();
            rowData[2] = buketi.getPriceB();
            rowData[3] = buketi.getKolB();
            rowData[4] = buketi.getPriceB() * buketi.getKolB();
            model.addRow(rowData);
        }
        // TODO add your handling code here:
    }*/
    
        private void doClearTable(){
          while (model.getRowCount()>0){
          model.removeRow(0);
                }
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buy;
    private javax.swing.JButton Contacts;
    private javax.swing.JButton Exit;
    private javax.swing.JToolBar.Separator Jspersad;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddB;
    private javax.swing.JButton btnAddF;
    private javax.swing.JButton btnAddKM;
    private javax.swing.JButton btnAddRM;
    private javax.swing.JButton btnAddSJ;
    private javax.swing.JButton btnBuketi;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCancelB;
    private javax.swing.JButton btnCancelF;
    private javax.swing.JButton btnCancelKM;
    private javax.swing.JButton btnCancelRM;
    private javax.swing.JButton btnCancelSJ;
    private javax.swing.JButton btnDecide;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFlover;
    private javax.swing.JButton btnKM;
    private javax.swing.JButton btnPostav;
    private javax.swing.JButton btnRM;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSJ;
    private javax.swing.JComboBox cmbNameB;
    private javax.swing.JComboBox cmbNameF;
    private javax.swing.JComboBox cmbNameKM;
    private javax.swing.JComboBox cmbNameRM;
    private javax.swing.JComboBox cmbNameSJ;
    private javax.swing.JDialog dlgAddBuketi;
    private javax.swing.JDialog dlgAddFlover;
    private javax.swing.JDialog dlgCat;
    private javax.swing.JDialog dlgContacts;
    private javax.swing.JDialog dlgKM;
    private javax.swing.JDialog dlgPost;
    private javax.swing.JDialog dlgRM;
    private javax.swing.JDialog dlgSJ;
    private javax.swing.JDialog dlgTabl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblPriceInfoB;
    private javax.swing.JLabel lblPriceInfoF;
    private javax.swing.JLabel lblPriceInfoKM;
    private javax.swing.JLabel lblPriceInfoRM;
    private javax.swing.JLabel lblPriceInfoSJ;
    private javax.swing.JScrollBar scrPriceB;
    private javax.swing.JScrollBar scrPriceF;
    private javax.swing.JScrollBar scrPriceKM;
    private javax.swing.JScrollBar scrPriceRM;
    private javax.swing.JScrollBar scrPriceSJ;
    private javax.swing.JSpinner spnKolB;
    private javax.swing.JSpinner spnKolF;
    private javax.swing.JSpinner spnKolKM;
    private javax.swing.JSpinner spnKolRM;
    private javax.swing.JSpinner spnKolSJ;
    private javax.swing.JTable tbl;
    private javax.swing.JToolBar tlBar;
    private javax.swing.JTextField txt;
    // End of variables declaration//GEN-END:variables
}
